description: Cors Http Handler
enabled: true
allowedOrigins:
  #  - http://localhost:4200
  # http://localhost:3000
  # - http://localhost:3001
  - https://visoftapp1.visoft-eng.com
  - http://visoft-test.visoft-eng.com:8090
  - http://visoftapp1.visoft-eng.com:8090
  - http://visoftapp1.visoft-eng.com:8180
  - http://10.10.10.15:8180
  - http://10.10.10.68:8180
  - http://10.10.10.65:8090
  - http://10.10.10.70:8090
  - http://visoftapp1.visoft-eng.com:3002
allowedMethods:
  - GET
  - POST
  - DELETE
  - PUT

  
