#
# Singleton service factory configuration/IoC injection
singletons:
# HandlerProvider implementation
- com.networknt.server.HandlerProvider:
    - com.visoft.file.service.web.handler.GeneralHandlerProvider
- com.networknt.handler.MiddlewareHandler:
  # Exception Global exception handler that needs to be called first to wrap all middleware handlers and business handlers
  - com.networknt.exception.ExceptionHandler
  # Metrics handler to calculate response time accurately, this needs to be the second handler in the chain.
  - com.networknt.metrics.MetricsHandler
  # Traceability Put traceabilityId into response header from request header if it exists
  - com.networknt.traceability.TraceabilityHandler
  # Correlation Create correlationId if it doesn't exist in the request header and put it into the request header
  - com.networknt.correlation.CorrelationHandler
  # SimpleAudit Log important info about the request into audit log
  - com.networknt.audit.AuditHandler
  #Cors handler to handler post/put pre-flight
#  - com.networknt.cors.CorsHttpHandler:
  - com.visoft.file.service.web.cors.CorsHttpHandler
  - com.visoft.file.service.web.security.SecurityHandler
- com.visoft.file.service.startup.AdminCreator:
    - com.visoft.file.service.startup.AdminCreator
- com.visoft.file.service.startup.Scheduler:
    - com.visoft.file.service.startup.Scheduler