pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'export PATH=/home/visrvadmin/jdk/openlogic-openjdk-8u292-b10-linux-x64/bin:${PATH}; mvn -B clean package -DskipTests'
                if (env.USER_AT_HOST == 'visrvadmin@10.10.10.70') {
                        sh """         
                            rm ./src/main/resources/application.properties
                            mv ./src/main/resources/application-test.properties  ./src/main/resources/application.properties
                        """
                }                
               
            }
   
        }   
        stage('Deliver') { 
            steps {
                sh """
                 ssh -p 57122 ${USER_AT_HOST} rm -rf /home/visrvadmin/vi-soft/fileServer/jar-dir
                 ssh -p 57122 ${USER_AT_HOST} mkdir /home/visrvadmin/vi-soft/fileServer/jar-dir
                 scp -P 57122 ~/workspace/fileServer/target/file_server-0.0.1.jar ${USER_AT_HOST}:~/vi-soft/fileServer/jar-dir/.
                 scp -P 57122 ~/workspace/fileServer/ci/* ${USER_AT_HOST}:~/vi-soft/fileServer/.
                 ssh -p 57122 ${USER_AT_HOST} chmod 700 /home/visrvadmin/vi-soft/fileServer/${DEPLOY_FILE}
                 ssh -p 57122 ${USER_AT_HOST} /home/visrvadmin/vi-soft/fileServer/${DEPLOY_FILE}
                """
            }
        }
    }
}
